spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/url_shortener
      username: root
      password: password
      maximum-pool-size: 3
    url: ${spring.datasource.hikari.jdbc-url}
  data:
    redis:
      host: localhost
      port: 16379
      password: password
      timeout: 60000
      clientName: url-shortener

config:
  app:
    host: http://localhost:8080
