spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/url_shortener
      username: root
      password: password
      minimum-idle: 10
      maximum-pool-size: 20
    url: ${spring.datasource.hikari.jdbc-url}
  data:
    redis:
      host: localhost
      port: 16379
      password: password
      timeout: 60000
      clientName: url-shortener
